webtalk_init -webtalk_dir C:\\Users\\Surya\\Desktop\\zed_labs\\new_audio_v2\\ZedBoard_FreeRTOS_WorkSpace_V3_1_1\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 26 11:11:46 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6np2rh8dhscllpbofrem3gue0e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1456502950745" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1456502950745"
webtalk_add_data -client sdk -key uid -value "1456502992389" -context "sdk\\\\bsp/1456502992389"
webtalk_add_data -client sdk -key hwid -value "1456502950745" -context "sdk\\\\bsp/1456502992389"
webtalk_add_data -client sdk -key os -value "freertos823_xilinx" -context "sdk\\\\bsp/1456502992389"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1456502992389"
webtalk_add_data -client sdk -key uid -value "1456503006926" -context "sdk\\\\application/1456503006926"
webtalk_add_data -client sdk -key hwid -value "1456502950745" -context "sdk\\\\application/1456503006926"
webtalk_add_data -client sdk -key bspid -value "1456502992389" -context "sdk\\\\application/1456503006926"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1456503006926"
webtalk_add_data -client sdk -key os -value "freertos823_xilinx" -context "sdk\\\\application/1456503006926"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1456503006926"
webtalk_transmit -clientid 662437190 -regid "" -xml C:\\Users\\Surya\\Desktop\\zed_labs\\new_audio_v2\\ZedBoard_FreeRTOS_WorkSpace_V3_1_1\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Surya\\Desktop\\zed_labs\\new_audio_v2\\ZedBoard_FreeRTOS_WorkSpace_V3_1_1\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Surya\\Desktop\\zed_labs\\new_audio_v2\\ZedBoard_FreeRTOS_WorkSpace_V3_1_1\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
